name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake in SVG format
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: NxSYED-ux
          output_file: github-contribution-grid-snake.svg

      # Commit and push changes
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git diff-index --quiet HEAD || git commit -m "Update contribution snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
